# Working with Text Data in pandas

# Exercise 1 (2 points)

Load the `pandas` library.

In [1]:
import pandas as pd

# Exercise 2 (3 points)

Create a `pandas` data-frame called `df` with the `time_sentences` list:

```
time_sentences = ["Monday: The doctor's appointment is at 2:45pm.", 
                  "Tuesday: The dentist's appointment is at 11:30 am.",
                  "Wednesday: At 7:00pm, there is a basketball game!",
                  "Thursday: Be back home by 11:15 pm at the latest.",
                  "Friday: Take the train at 08:10 am, arrive at 09:00am."]
```

In [6]:
time_sentences = {'Sentences' : ["Monday: The doctor's appointment is at 2:45pm.", 
                  "Tuesday: The dentist's appointment is at 11:30 am.",
                  "Wednesday: At 7:00pm, there is a basketball game!",
                  "Thursday: Be back home by 11:15 pm at the latest.",
                  "Friday: Take the train at 08:10 am, arrive at 09:00am."]
}
df = pd.DataFrame(time_sentences)
df.head()

                                           Sentences
0     Monday: The doctor's appointment is at 2:45pm.
1  Tuesday: The dentist's appointment is at 11:30...
2  Wednesday: At 7:00pm, there is a basketball game!
3  Thursday: Be back home by 11:15 pm at the latest.
4  Friday: Take the train at 08:10 am, arrive at ...

# Exercise 3 (2 points)

Report the number of characters of each of the sentences in the `df` data-frame.

In [7]:
df['Sentences'].str.len()

0    46
1    50
2    49
3    49
4    54
Name: Sentences, dtype: int64

# Exercise 4 (2 points)

Report the number of tokens for each sentence in the `df` data-frame.

In [8]:
df['Sentences'].str.split().str.len()

0     7
1     8
2     8
3    10
4    10
Name: Sentences, dtype: int64

# Exercise 5 (2 points)

Report the sentences that contain the word `appointment` in the `df` data-frame.

In [10]:
# I went ahead and did this part for fun :)
df[df['Sentences'].str.contains('appointment', case=False, na=False)]

                                           Sentences
0     Monday: The doctor's appointment is at 2:45pm.
1  Tuesday: The dentist's appointment is at 11:30...

# Exercise 6 (3 points)

Replace weekdays with their 3 letter abbreviations.

In [12]:
df['Sentences'] = df['Sentences'].replace({
    'Monday': 'Mon',
    'Tuesday': 'Tues', 
    'Wednesday': 'Wed',
    'Thursday': 'Thur', 
    'Friday': 'Fri'
}, regex=True)

df.head()

                                           Sentences
0        Mon: The doctor's appointment is at 2:45pm.
1    Tues: The dentist's appointment is at 11:30 am.
2        Wed: At 7:00pm, there is a basketball game!
3      Thur: Be back home by 11:15 pm at the latest.
4  Fri: Take the train at 08:10 am, arrive at 09:...